import type { Aos4ImportDiagnostic, Aos4ImportSource, Aos4ParsedRosterResult } from '../aos4/import'

export const MAX_TEXT_IMPORT_BYTES = 1024 * 1024
export const MAX_TEXT_IMPORT_LINES = 10_000
export const MAX_IMPORT_SELECTIONS = 1_000

export type Aos4TextImportSource = Extract<
  Aos4ImportSource,
  'official-app-text' | 'listbot-text' | 'sigdex-text'
>

export interface Aos4ImportLine {
  number: number
  text: string
}

export interface Aos4TextDetectionResult {
  source?: Aos4TextImportSource
  lines: Aos4ImportLine[]
  diagnostics: Aos4ImportDiagnostic[]
}

const officialCreatedPattern = /^Created with Warhammer Age of Sigmar: The App$/i
const officialVersionPatterns = [
  /^App:\s*\S.+\|\s*Data:\s*\S.+$/i,
  /^Exported with App Version:\s*\S.+\s+Data Version:\s*\S.+$/i,
]
const listbotFooterPattern = /^Generated by Listbot 4\.0$/
const sigdexFooterPattern = /^Created with Sigdex:\s*https:\/\/sigdex\.io\/?$/i

const error = (code: Aos4ImportDiagnostic['code'], message: string, line?: number) => ({
  code,
  severity: 'error' as const,
  message,
  ...(line === undefined ? {} : { line }),
})

export const detectAos4TextSource = (input: string): Aos4TextDetectionResult => {
  if (new TextEncoder().encode(input).byteLength > MAX_TEXT_IMPORT_BYTES) {
    return {
      lines: [],
      diagnostics: [
        error('input-too-large', `Roster text must be ${MAX_TEXT_IMPORT_BYTES} bytes or smaller.`),
      ],
    }
  }
  if (input.includes('\0')) {
    return {
      lines: [],
      diagnostics: [error('unsafe-input', 'Roster text contains a null byte and cannot be imported.')],
    }
  }

  const lines = input
    .normalize('NFKC')
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((text, index) => ({ number: index + 1, text: text.trim() }))

  if (lines.length > MAX_TEXT_IMPORT_LINES) {
    return {
      lines: [],
      diagnostics: [
        error('input-too-large', `Roster text must contain ${MAX_TEXT_IMPORT_LINES} lines or fewer.`),
      ],
    }
  }

  const createdLine = lines.find(line => officialCreatedPattern.test(line.text))
  const versionLine = lines.find(line => officialVersionPatterns.some(pattern => pattern.test(line.text)))
  const listbotLine = lines.find(line => listbotFooterPattern.test(line.text))
  const sigdexLine = lines.find(line => sigdexFooterPattern.test(line.text))
  const matches: Aos4TextImportSource[] = []
  if (createdLine && versionLine) matches.push('official-app-text')
  if (listbotLine) matches.push('listbot-text')
  if (sigdexLine) matches.push('sigdex-text')

  if (matches.length !== 1) {
    return {
      lines,
      diagnostics: [
        error(
          'unsupported-source',
          matches.length
            ? 'Roster text contains markers for more than one supported source.'
            : 'Roster text is not a supported current official app, Listbot 4.0, or Sigdex export.',
          listbotLine?.number ?? sigdexLine?.number ?? createdLine?.number ?? versionLine?.number
        ),
      ],
    }
  }

  return { source: matches[0], lines, diagnostics: [] }
}

export const enforceParsedSelectionLimit = (result: Aos4ParsedRosterResult): Aos4ParsedRosterResult => {
  if (!result.parsedRoster || result.parsedRoster.selections.length <= MAX_IMPORT_SELECTIONS) {
    return result
  }
  return {
    diagnostics: [
      error(
        'input-too-large',
        `A roster may contain at most ${MAX_IMPORT_SELECTIONS} recognized selections.`
      ),
    ],
  }
}
