import type { Aos4ParsedRosterResult, ParsedRosterSelection, ParsedRosterSelectionKind } from '../aos4/import'
import type { Aos4ImportLine } from './detectTextSource'

const footerPattern = /^Generated by Listbot 4\.0$/
const contextPattern = /^(?:General['’]s Handbook|GHB)\b/i
const lorePattern = /^(Spell Lore|Prayer Lore|Manifestation Lore)\s*[-:]\s*(.+)$/i
const pointsLinePattern =
  /^-\s*(?:(\d+)\s*[x×]\s+)?(.+?)\s+\(\s*\d+\s*(?:pts?|points?)?\s*\)\s*$|^(?:(\d+)\s*[x×]\s+)?(.+?)\s+\(\s*\d+\s*(?:pts?|points?)?\s*\)\s*$/i
const metadataPattern = /^(?:Regiment|Auxiliary|Drops?:|Total:|Points?:)/i
/**
 * A bracketed enhancement may carry its cost — `[Bloodshadow Rites (20pts)]`. The cost is roster
 * bookkeeping, and leaving it on the label is the difference between resolving the enhancement and
 * silently dropping it.
 */
const pointsSuffixPattern = /\s*\(\s*\+?\d+\s*(?:pts?|points?)?\s*\)\s*$/i

const stripPointsSuffix = (value: string): string => value.replace(pointsSuffixPattern, '').trim()

const loreKind = (label: string): ParsedRosterSelectionKind => {
  if (/^Prayer Lore$/i.test(label)) return 'prayer-lore'
  if (/^Manifestation Lore$/i.test(label)) return 'manifestation-lore'
  return 'spell-lore'
}

const parseBracket = (line: Aos4ImportLine): ParsedRosterSelection | undefined => {
  const match = line.text.match(/^\[(.+)\]$/)
  if (!match) return undefined
  const label = stripPointsSuffix(match[1])
  if (/^(?:General|Reinforced)$/i.test(label) || /\bx\d+\b/i.test(label) || label.includes(';')) {
    return undefined
  }
  const typed = label.match(
    /^(Artefact of Power|Spell Lore|Prayer Lore|Manifestation Lore|Heroic Trait)\s*[-:]\s*(.+)$/i
  )
  if (!typed) return { line: line.number, label, kindHint: 'enhancement' }
  const kindHint = /^Artefact of Power$/i.test(typed[1])
    ? 'artefact-of-power'
    : /^Heroic Trait$/i.test(typed[1])
      ? 'enhancement'
      : loreKind(typed[1])
  return { line: line.number, label: stripPointsSuffix(typed[2]), kindHint }
}

const parseWarscroll = (line: Aos4ImportLine): ParsedRosterSelection | undefined => {
  const match = line.text.match(pointsLinePattern)
  if (!match) return undefined
  const count = match[1] ?? match[3]
  const label = match[2] ?? match[4]
  return {
    line: line.number,
    label: label.trim(),
    kindHint: 'warscroll',
    ...(count ? { count: Number(count) } : {}),
  }
}

export const parseListbotRoster = (lines: Aos4ImportLine[]): Aos4ParsedRosterResult => {
  const populated = lines.filter(line => line.text && !footerPattern.test(line.text))
  const factionLine = populated[0]
  const formationLine = populated[1]
  if (!factionLine || !formationLine) {
    return {
      diagnostics: [
        {
          code: 'missing-faction',
          severity: 'error',
          message: 'The Listbot export must begin with a faction and battle formation.',
          ...(factionLine ? { line: factionLine.number } : {}),
        },
      ],
    }
  }

  const selections: ParsedRosterSelection[] = [
    {
      line: formationLine.number,
      label: formationLine.text,
      kindHint: 'battle-formation',
    },
  ]
  let declaredContext: string | undefined
  /** The most recent unit line, so a bracketed enhancement under it knows its bearer (#1989). */
  let lastWarscrollLine: number | undefined

  populated.slice(2).forEach(line => {
    if (contextPattern.test(line.text)) {
      declaredContext = line.text
      return
    }
    if (metadataPattern.test(line.text)) return
    const lore = line.text.match(lorePattern)
    if (lore) {
      selections.push({ line: line.number, label: lore[2].trim(), kindHint: loreKind(lore[1]) })
      return
    }
    const bracket = parseBracket(line)
    if (bracket) {
      const carried =
        lastWarscrollLine !== undefined &&
        (bracket.kindHint === 'enhancement' || bracket.kindHint === 'artefact-of-power')
      selections.push(carried ? { ...bracket, bearerLine: lastWarscrollLine } : bracket)
      return
    }
    const warscroll = parseWarscroll(line)
    if (warscroll) {
      selections.push(warscroll)
      lastWarscrollLine = warscroll.line
    }
  })

  return {
    parsedRoster: {
      source: 'listbot-text',
      proposedName: `${factionLine.text} — ${formationLine.text}`,
      declaredFaction: factionLine.text,
      ...(declaredContext ? { declaredContext } : {}),
      selections,
    },
    diagnostics: [],
  }
}
