import React from 'react'

import { ISelections } from 'types/selections'
import { titleCase } from 'utils/titleCase'

export const PrintHeader = (props: { factionName: string }) => {
  return (
    <header className={'text-center mt-4 mb-1 d-none d-print-block'}>
      <h1>AoS Reminders - {titleCase(props.factionName)}</h1>
    </header>
  )
}

export const PrintUnits = (props: { selections: ISelections; realmscape: string }) => {
  const { units, battalions, artifacts, traits } = props.selections
  const realm = props.realmscape === 'None' ? [] : [props.realmscape]
  return (
    <div className={'row text-center d-none d-print-block'}>
      <ItemsDisplay name={'Unit'} items={units} />
      <ItemsDisplay name={'Artifact'} items={artifacts} />
      <ItemsDisplay name={'Battalion'} items={battalions} />
      <ItemsDisplay name={'Command Trait'} items={traits} />
      <ItemsDisplay name={'Realmscape Feature'} items={realm} />
    </div>
  )
}

const ItemsDisplay = (props: { name: string; items: string[] }) => {
  if (!props.items.length) return null
  const title = props.items.length > 1 ? `${props.name}s` : props.name
  return (
    <p>
      <strong>{title}:</strong> {props.items.join(' | ')}
    </p>
  )
}

export const PrintFooter = () => {
  return (
    <footer className={'text-center pb-4 pt-1 d-none d-print-block'}>
      Generated by <strong>AoS Reminders</strong>
      <br />
      <strong>daviseford.com/aos-reminders/</strong>
    </footer>
  )
}
