import React from 'react'

const PrintFooter = () => {
  return (
    <footer className={'text-center py-3 d-none d-print-block'}>
      Generated by <strong>AoS Reminders</strong>
      <br />
      <strong>aosreminders.com</strong>
    </footer>
  )
}

export default PrintFooter
