import React from 'react'
import { connect } from 'react-redux'

import { ISelections, IAllySelections } from 'types/selections'
import { titleCase } from 'utils/titleCase'
import { factionNames, selections, realmscape } from 'ducks'

const PrintHeaderComponent = (props: { factionName: string }) => {
  return (
    <header className={'text-center mt-4 mb-1 d-none d-print-block'}>
      <h1>AoS Reminders - {titleCase(props.factionName)}</h1>
    </header>
  )
}

const mapHeaderStateToProps = (state, ownProps) => ({
  ...ownProps,
  factionName: factionNames.selectors.getFactionName(state),
})

export const PrintHeader = connect(
  mapHeaderStateToProps,
  null
)(PrintHeaderComponent)

const PrintUnitsComponent = (props: {
  selections: ISelections
  allySelections: IAllySelections
  realmscape: string
}) => {
  const { units, battalions, artifacts, traits } = props.selections
  const { units: allyUnits } = props.allySelections
  const realm = props.realmscape === 'None' ? [] : [props.realmscape]
  return (
    <div className={'row text-center d-none d-print-block'}>
      <ItemsDisplayComponent name={'Unit'} items={units} />
      <ItemsDisplayComponent name={'Allied Unit'} items={allyUnits} />
      <ItemsDisplayComponent name={'Artifact'} items={artifacts} />
      <ItemsDisplayComponent name={'Battalion'} items={battalions} />
      <ItemsDisplayComponent name={'Command Trait'} items={traits} />
      <ItemsDisplayComponent name={'Realmscape Feature'} items={realm} />
    </div>
  )
}

const mapUnitsStateToProps = (state, ownProps) => ({
  allySelections: selections.selectors.getAllySelections(state),
  realmscape: realmscape.selectors.getRealmscape(state),
  selections: selections.selectors.getSelections(state),
})

export const PrintUnits = connect(
  mapUnitsStateToProps,
  null
)(PrintUnitsComponent as any)

const ItemsDisplayComponent = (props: { name: string; items: string[] }) => {
  if (!props.items.length) return null
  const title = props.items.length > 1 ? `${props.name}s` : props.name
  return (
    <p className="py-0 my-0">
      <strong>{title}:</strong> {props.items.join(' | ')}
    </p>
  )
}

export const PrintFooterComponent = () => {
  return (
    <footer className={'text-center pb-4 pt-1 d-none d-print-block'}>
      Generated by <strong>AoS Reminders</strong>
      <br />
      <strong>daviseford.com/aos-reminders/</strong>
    </footer>
  )
}
