import fs from 'node:fs'
import path from 'node:path'

import { decodeAos4RosterFile, decodeAos4TextRoster } from '../../importers'

const fixture = (name: string): string =>
  fs.readFileSync(path.resolve(process.cwd(), 'src/tests/fixtures/aos4/import/listbot', name), 'utf8')

describe('Listbot 4.0 text import', () => {
  it('decodes regiment structure while ignoring general and weapon configuration metadata', () => {
    const result = decodeAos4TextRoster(fixture('regiments.txt'))

    expect(result.diagnostics).toEqual([])
    expect(result.parsedRoster).toMatchObject({
      source: 'listbot-text',
      proposedName: "Skaven — Thanquol's Mutated Menagerie",
      declaredFaction: 'Skaven',
    })
    expect(result.parsedRoster?.declaredContext).toBeUndefined()
    expect(result.parsedRoster?.selections).toEqual([
      {
        line: 2,
        label: "Thanquol's Mutated Menagerie",
        kindHint: 'battle-formation',
      },
      { line: 5, label: 'Master Moulder', kindHint: 'warscroll' },
      { line: 7, label: 'Warpstone Innards', kindHint: 'enhancement' },
      { line: 8, label: 'Stormfiends', kindHint: 'warscroll', count: 6 },
    ])
  })

  it('preserves typed lore and enhancement selections with stable source lines', () => {
    const result = decodeAos4TextRoster(fixture('enhancements.txt'))

    expect(result.diagnostics).toEqual([])
    expect(result.parsedRoster).toMatchObject({
      source: 'listbot-text',
      proposedName: 'Soulblight Gravelords — Deathmarch',
      declaredFaction: 'Soulblight Gravelords',
      declaredContext: "General's Handbook 2026-27",
    })
    expect(result.parsedRoster?.selections).toEqual([
      { line: 2, label: 'Deathmarch', kindHint: 'battle-formation' },
      { line: 5, label: 'Lore of Undeath', kindHint: 'spell-lore' },
      { line: 8, label: 'Vampire Lord', kindHint: 'warscroll' },
      { line: 9, label: 'Amulet of Screams', kindHint: 'artefact-of-power' },
      { line: 10, label: 'Unbending Will', kindHint: 'enhancement' },
      {
        line: 11,
        label: 'Deathrattle Skeletons',
        kindHint: 'warscroll',
        count: 20,
      },
    ])
  })

  it('enforces the recognized-selection limit', () => {
    const units = Array.from({ length: 1_001 }, (_, index) => `- Unit ${index} (100)`).join('\n')
    const result = decodeAos4TextRoster(`Faction\nFormation\n${units}\nGenerated by Listbot 4.0`)

    expect(result.parsedRoster).toBeUndefined()
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'input-too-large', severity: 'error' })
    )
  })

  it('decodes a Listbot text export from a roster file and rejects invalid UTF-8', async () => {
    const text = fixture('regiments.txt')
    const uploaded = await decodeAos4RosterFile({
      name: 'skaven-listbot.txt',
      bytes: new TextEncoder().encode(text),
    })
    const invalid = await decodeAos4RosterFile({
      name: 'invalid-listbot.txt',
      bytes: new Uint8Array([0xc3, 0x28]),
    })

    expect(uploaded.diagnostics).toEqual([])
    expect(uploaded.parsedRoster).toMatchObject({
      source: 'listbot-text',
      declaredFaction: 'Skaven',
      proposedName: "Skaven — Thanquol's Mutated Menagerie",
    })
    expect(invalid.parsedRoster).toBeUndefined()
    expect(invalid.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'unsafe-input', severity: 'error' })
    )
  })
})
