// @vitest-environment jsdom

import ImportArmyModal from 'components/input/importArmy/importArmyModal'
import { useSubscriberAction } from 'components/input/importArmy/subscriberAction'
import { AOS4_CATALOG } from '../../aos4/generated'
import { MAX_ROSTER_FILE_BYTES } from '../../importers/aos4'
import { render, unmountComponentAtNode } from 'tests/support/reactTestHelpers'
import { act } from 'react'
import { Simulate } from 'tests/support/reactTestHelpers'
import { MemoryRouter, Route } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

const auth = vi.hoisted(() => ({
  isAuthenticated: false,
  isLoading: false,
}))
const subscription = vi.hoisted(() => ({
  isActive: false,
  subscriptionLoading: false,
}))
const login = vi.hoisted(() => vi.fn())

vi.mock('@auth0/auth0-react', () => ({
  useAuth0: () => auth,
}))

vi.mock('context/useSubscription', () => ({
  useSubscription: () => subscription,
}))

vi.mock('utils/hooks/useLogin', () => ({
  default: () => ({ isLoggingIn: false, login }),
}))

vi.mock('context/useTheme', () => ({
  useTheme: () => ({
    isDark: false,
    theme: {
      bgColor: 'bg-white',
      dropzone: 'dropzone',
      genericButton: 'btn btn-outline-dark',
      modalConfirmClass: 'btn btn-outline-dark',
      modalDangerClass: 'btn btn-outline-danger',
      modalSuccessClass: 'btn btn-success',
      text: 'text-dark',
    },
  }),
}))

vi.mock('components/modals/generic/generic_modal', () => ({
  default: ({ children, isOpen, label }: React.PropsWithChildren<{ isOpen: boolean; label: string }>) =>
    isOpen ? (
      <div aria-label={label} role="dialog">
        {children}
      </div>
    ) : null,
}))

const officialRoster = (unit = 'Annihilators', includeContext = true) => `Thunderhost 1000/1000 pts
Stormcast Eternals
Thunderhead Host
${includeContext ? "General's Handbook 2026-27" : ''}

REGIMENTS
Gardus Steel Soul (160)
${unit} (160)

Created with Warhammer Age of Sigmar: The App
App: 1.20.0 | Data: 345`

const rosterXml = `<?xml version="1.0" encoding="UTF-8"?>
<roster id="r1" name="Uploaded Stormhost" battleScribeVersion="2.03"
  gameSystemName="Age of Sigmar 4.0" xmlns="http://www.battlescribe.net/schema/rosterSchema">
  <forces>
    <force id="f1" name="General's Handbook 2026-27" catalogueName="Stormcast Eternals">
      <forces>
        <force id="f2" name="Regiment" catalogueName="Stormcast Eternals">
          <selections>
            <selection id="u1" name="Annihilators" number="1" type="unit" />
          </selections>
        </force>
      </forces>
    </force>
  </forces>
</roster>`

const listbotRoster = `Skaven
Thanquol's Mutated Menagerie

Regiment 1
Master Moulder (90)
[General]
[Warpstone Innards]
- 6 x Stormfiends (520)
[Doomflayer Gauntlets x2 ; Grinderfists x2]

Drops: 2
Total: 1000 / 1000
Generated by Listbot 4.0`

const findButton = (container: HTMLElement, label: string): HTMLButtonElement => {
  const button = Array.from(container.querySelectorAll('button')).find(
    candidate => candidate.textContent?.trim() === label
  )
  if (!button) throw new Error(`Button "${label}" not found`)
  return button
}

/**
 * `Simulate`'s event data type predates drag events and has no `dataTransfer`, so the dropped file
 * is attached through a cast rather than left untested.
 */
const dropEventData = (file: File): Parameters<typeof Simulate.drop>[1] =>
  ({ dataTransfer: { files: [file] } }) as unknown as Parameters<typeof Simulate.drop>[1]

const SubscriberActionHarness = ({ onAuthorized }: { onAuthorized: () => void }) => {
  const action = useSubscriberAction({ onAuthorized, origin: 'SubscriberActionTest' })
  return (
    <button disabled={action.disabled} onClick={action.run} type="button">
      Subscriber action
    </button>
  )
}

describe('subscriber-only account action', () => {
  let container: HTMLDivElement

  beforeEach(() => {
    auth.isAuthenticated = false
    auth.isLoading = false
    subscription.isActive = false
    subscription.subscriptionLoading = false
    login.mockReset()
    container = document.createElement('div')
    document.body.appendChild(container)
  })

  afterEach(() => {
    act(() => {
      unmountComponentAtNode(container)
    })
    container.remove()
  })

  it('opens login for signed-out users, Subscribe for inactive users, and paid actions for subscribers', () => {
    const onAuthorized = vi.fn()
    const renderHarness = () =>
      render(
        <MemoryRouter initialEntries={['/']}>
          <SubscriberActionHarness onAuthorized={onAuthorized} />
          <Route path="/subscribe">Subscribe destination</Route>
        </MemoryRouter>,
        container
      )

    act(() => {
      renderHarness()
    })
    act(() => {
      Simulate.click(container.querySelector('button')!)
    })
    expect(login).toHaveBeenCalledTimes(1)
    expect(onAuthorized).not.toHaveBeenCalled()

    auth.isAuthenticated = true
    act(() => {
      renderHarness()
    })
    act(() => {
      Simulate.click(container.querySelector('button')!)
    })
    expect(container.textContent).toContain('Subscribe destination')
    expect(onAuthorized).not.toHaveBeenCalled()

    act(() => {
      unmountComponentAtNode(container)
    })
    subscription.isActive = true
    act(() => {
      renderHarness()
    })
    act(() => {
      Simulate.click(container.querySelector('button')!)
    })
    expect(onAuthorized).toHaveBeenCalledTimes(1)
  })
})

describe('AoS 4 import modal', () => {
  let container: HTMLDivElement
  let onApply: ReturnType<typeof vi.fn>
  let closeModal: ReturnType<typeof vi.fn>

  const renderModal = () => {
    render(
      <ImportArmyModal
        closeModal={closeModal}
        createDocumentId={() => 'army:import-ui-test'}
        isOpen
        onApply={onApply}
      />,
      container
    )
  }

  const pasteAndPreview = (text: string) => {
    if (!container.querySelector('textarea')) {
      act(() => {
        Simulate.click(findButton(container, 'Paste roster'))
      })
    }
    const textarea = container.querySelector('textarea')!
    textarea.value = text
    act(() => {
      Simulate.change(textarea)
    })
    act(() => {
      Simulate.click(findButton(container, 'Preview import'))
    })
  }

  beforeEach(() => {
    onApply = vi.fn()
    closeModal = vi.fn()
    container = document.createElement('div')
    document.body.appendChild(container)
    act(() => {
      renderModal()
    })
  })

  afterEach(() => {
    act(() => {
      unmountComponentAtNode(container)
    })
    container.remove()
  })

  it('previews and atomically applies a supported pasted roster with a fresh local document', () => {
    pasteAndPreview(officialRoster())

    expect(container.textContent).toContain('Warhammer Age of Sigmar app')
    expect(container.textContent).toContain('Stormcast Eternals')
    expect(container.textContent).toContain('Thunderhead Host')
    const apply = findButton(container, 'Import Army')
    expect(apply.disabled).toBe(false)

    act(() => {
      Simulate.click(apply)
    })

    expect(onApply).toHaveBeenCalledTimes(1)
    expect(onApply.mock.calls[0][0]).toMatchObject({
      id: 'army:import-ui-test',
      name: 'Thunderhost',
      reminderPreferences: {},
    })
    expect(onApply.mock.calls[0][0].explicitSelectionIds.length).toBeGreaterThan(1)
  })

  /**
   * A name we cannot place is shown and skipped, not treated as a dead end. The player came from a
   * builder where the unit exists, so the useful outcome is the rest of the army plus a note about
   * what was dropped.
   */
  it('stays confirmable when a selection cannot be placed, and names it', () => {
    pasteAndPreview(officialRoster('Annihilators', false))

    expect(container.textContent).toContain('No rules context was declared')
    expect(findButton(container, 'Import Army').disabled).toBe(false)

    pasteAndPreview(officialRoster('Definitely Unknown Unit'))

    expect(container.textContent).toContain('Definitely Unknown Unit')
    expect(findButton(container, 'Import Army').disabled).toBe(false)

    act(() => {
      Simulate.click(findButton(container, 'Import Army'))
    })
    expect(onApply).toHaveBeenCalledTimes(1)
  })

  /**
   * The roster usually settles the ruleset itself, and asking anyway invites the player to change
   * an answer they never gave. The question appears only where one is genuinely missing.
   */
  it('asks which ruleset to use only when the roster declares none we carry', () => {
    pasteAndPreview(officialRoster())
    expect(container.querySelector('#import-rules-context')).toBeNull()

    pasteAndPreview(officialRoster('Annihilators', false))
    expect(container.textContent).toContain('Which ruleset do you want to use?')

    const select = container.querySelector<HTMLSelectElement>('#import-rules-context')!
    const spearhead = Array.from(select.options).find(option => option.textContent?.includes('Spearhead'))!
    select.value = spearhead.value
    act(() => {
      Simulate.change(select)
    })

    expect(container.querySelector<HTMLSelectElement>('#import-rules-context')!.value).toBe(spearhead.value)
    expect(container.textContent).toContain('Age of Sigmar Fourth Edition Spearhead')
  })

  /**
   * Uploading is the common path, so the modal opens on it — no click to switch modes here.
   */
  it('opens on the upload zone and previews a roster dropped onto it', async () => {
    const file = new File([rosterXml], 'stormhost.ros', { type: 'application/xml' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(rosterXml).buffer,
    })
    const dropzone = container.querySelector<HTMLDivElement>('.dropzone')!

    await act(async () => {
      Simulate.drop(dropzone, dropEventData(file))
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(container.textContent).toContain('stormhost.ros')
    expect(container.textContent).toContain('Uploaded Stormhost')
    expect(findButton(container, 'Import Army').disabled).toBe(false)
  })

  it('previews a native .ros upload locally', async () => {
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File([rosterXml], 'stormhost.ros', { type: 'application/xml' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(rosterXml).buffer,
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(container.textContent).toContain('New Recruit roster file')
    expect(container.textContent).toContain('Uploaded Stormhost')
    expect(findButton(container, 'Import Army').disabled).toBe(false)
  })

  it('uploads a Listbot text file and applies its canonical composition', async () => {
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File([listbotRoster], 'skaven-listbot.txt', { type: 'text/plain' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(listbotRoster).buffer,
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(input.accept).toContain('.txt')
    expect(container.textContent).toContain('Listbot 4.0')
    expect(findButton(container, 'Import Army').disabled).toBe(false)

    act(() => {
      Simulate.click(findButton(container, 'Import Army'))
    })
    const imported = onApply.mock.calls[0][0]
    const entityById = new Map(AOS4_CATALOG.entities.map(entity => [entity.id, entity]))
    const importedNames = imported.explicitSelectionIds.map(id => entityById.get(id)?.name)
    expect(importedNames).toEqual(
      expect.arrayContaining(['Skaven', 'Master Moulder', 'Stormfiends', 'WARPSTONE INNARDS'])
    )
  })

  it('rejects an oversized roster before reading it into browser memory', async () => {
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File(['oversized'], 'oversized-listbot.txt', { type: 'text/plain' })
    const arrayBuffer = vi.fn(async () => new ArrayBuffer(0))
    Object.defineProperties(file, {
      arrayBuffer: { value: arrayBuffer },
      size: { value: MAX_ROSTER_FILE_BYTES + 1 },
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
    })

    expect(arrayBuffer).not.toHaveBeenCalled()
    expect(container.textContent).toContain(`Roster files must be ${MAX_ROSTER_FILE_BYTES} bytes or smaller.`)
    expect(findButton(container, 'Import Army').disabled).toBe(true)
  })

  it('cancels without applying or persisting the raw roster', () => {
    pasteAndPreview(officialRoster())
    act(() => {
      Simulate.click(findButton(container, 'Cancel'))
    })

    expect(closeModal).toHaveBeenCalledTimes(1)
    expect(onApply).not.toHaveBeenCalled()
  })
})
