import fs from 'node:fs'
import path from 'node:path'

import { decodeAos4TextRoster } from '../../importers/aos4'

const fixture = (name: string): string =>
  fs.readFileSync(path.resolve(process.cwd(), 'src/tests/fixtures/aos4/import/official-app', name), 'utf8')

describe('official AoS app text import', () => {
  it('decodes current app output into provider-neutral composition selections', () => {
    const result = decodeAos4TextRoster(fixture('current.txt'))

    expect(result.diagnostics).toEqual([])
    expect(result.parsedRoster).toMatchObject({
      source: 'official-app-text',
      proposedName: 'Sunhost',
      declaredFaction: 'Seraphon',
      declaredContext: "General's Handbook 2026-27",
    })
    expect(result.parsedRoster?.selections).toEqual([
      { line: 3, label: 'Thunderquake Starhost', kindHint: 'battle-formation' },
      { line: 6, label: 'Lore of Primal Jungles', kindHint: 'spell-lore' },
      { line: 9, label: 'Slann Starmaster', kindHint: 'warscroll' },
      { line: 11, label: 'Coatl Familiar', kindHint: 'enhancement' },
      { line: 12, label: 'Saurus Warriors', kindHint: 'warscroll', count: 2 },
      { line: 15, label: 'Realmshaper Engine', kindHint: 'warscroll' },
    ])
  })

  it('supports the exported-version footer, CRLF, pipe headers, and regiments of renown', () => {
    const result = decodeAos4TextRoster(fixture('exported-version.txt').replace(/\n/g, '\r\n'))

    expect(result.diagnostics).toEqual([])
    expect(result.parsedRoster).toMatchObject({
      source: 'official-app-text',
      proposedName: 'Skyhammer',
      declaredFaction: 'Stormcast Eternals',
    })
    expect(result.parsedRoster?.declaredContext).toBeUndefined()
    expect(result.parsedRoster?.selections).toEqual([
      {
        line: 2,
        label: 'Sentinels of the Bleak Citadels',
        kindHint: 'battle-formation',
      },
      { line: 6, label: 'Knight-Vexillor', kindHint: 'warscroll' },
      { line: 8, label: 'Mirrorshield', kindHint: 'enhancement' },
      { line: 9, label: 'Annihilators', kindHint: 'warscroll', count: 3 },
      { line: 13, label: 'Freeguild Fusiliers', kindHint: 'warscroll' },
      { line: 14, label: 'Freeguild Marshal', kindHint: 'warscroll' },
    ])
    expect(result.parsedRoster?.selections.map(selection => selection.label)).not.toContain(
      'The bearer shines with a rule description that is not roster composition.'
    )
  })

  it('rejects empty, stale, mixed, oversized, and overlong inputs without guessing a source', () => {
    const official = fixture('current.txt')
    const listbot = 'Skaven\nFormation\nGenerated by Listbot 4.0'
    const stale = 'Stormcast Eternals\nGenerated by Warscroll Builder'

    expect(decodeAos4TextRoster('').diagnostics).toContainEqual(
      expect.objectContaining({ code: 'unsupported-source', severity: 'error' })
    )
    expect(decodeAos4TextRoster(stale).diagnostics).toContainEqual(
      expect.objectContaining({ code: 'unsupported-source', severity: 'error' })
    )
    expect(decodeAos4TextRoster(`${official}\n${listbot}`).diagnostics).toContainEqual(
      expect.objectContaining({ code: 'unsupported-source', severity: 'error' })
    )
    expect(decodeAos4TextRoster(`x${'a'.repeat(1024 * 1024)}`).diagnostics).toContainEqual(
      expect.objectContaining({ code: 'input-too-large', severity: 'error' })
    )
    expect(
      decodeAos4TextRoster(Array.from({ length: 10_001 }, () => 'x').join('\n')).diagnostics
    ).toContainEqual(expect.objectContaining({ code: 'input-too-large', severity: 'error' }))
  })
})
