import fs from 'node:fs'
import path from 'node:path'

import { AOS4_CATALOG, AOS4_DEFAULT_RULES_CONTEXT_ID } from '../../aos4/generated'
import { resolveParsedRoster } from '../../aos4/import'
import { decodeAos4RosterFile, decodeAos4TextRoster } from '../../importers'

const fixture = (name: string): string =>
  fs.readFileSync(path.resolve(process.cwd(), 'src/tests/fixtures/aos4/import/listbot', name), 'utf8')

describe('Listbot 4.0 text import', () => {
  it('decodes regiment structure while ignoring general and weapon configuration metadata', () => {
    const result = decodeAos4TextRoster(fixture('regiments.txt'))

    expect(result.diagnostics).toEqual([])
    expect(result.parsedRoster).toMatchObject({
      source: 'listbot-text',
      proposedName: "Skaven — Thanquol's Mutated Menagerie",
      declaredFaction: 'Skaven',
    })
    expect(result.parsedRoster?.declaredContext).toBeUndefined()
    expect(result.parsedRoster?.selections).toEqual([
      {
        line: 2,
        label: "Thanquol's Mutated Menagerie",
        kindHint: 'battle-formation',
      },
      { line: 5, label: 'Master Moulder', kindHint: 'warscroll' },
      // The bracketed enhancement records its hero's line, so its bearer survives import (#1989).
      {
        line: 7,
        label: 'Warpstone Innards',
        kindHint: 'enhancement',
        bearer: { line: 5, label: 'Master Moulder' },
      },
      { line: 8, label: 'Stormfiends', kindHint: 'warscroll', count: 6 },
    ])
  })

  it('preserves typed lore and enhancement selections with stable source lines', () => {
    const result = decodeAos4TextRoster(fixture('enhancements.txt'))

    expect(result.diagnostics).toEqual([])
    expect(result.parsedRoster).toMatchObject({
      source: 'listbot-text',
      proposedName: 'Soulblight Gravelords — Deathmarch',
      declaredFaction: 'Soulblight Gravelords',
      declaredContext: "General's Handbook 2026-27",
    })
    expect(result.parsedRoster?.selections).toEqual([
      { line: 2, label: 'Deathmarch', kindHint: 'battle-formation' },
      { line: 5, label: 'Lore of Undeath', kindHint: 'spell-lore' },
      { line: 8, label: 'Vampire Lord', kindHint: 'warscroll' },
      {
        line: 9,
        label: 'Amulet of Screams',
        kindHint: 'artefact-of-power',
        bearer: { line: 8, label: 'Vampire Lord' },
      },
      {
        line: 10,
        label: 'Unbending Will',
        kindHint: 'enhancement',
        bearer: { line: 8, label: 'Vampire Lord' },
      },
      {
        line: 11,
        label: 'Deathrattle Skeletons',
        kindHint: 'warscroll',
        count: 20,
      },
    ])
  })

  it('enforces the recognized-selection limit', () => {
    const units = Array.from({ length: 1_001 }, (_, index) => `- Unit ${index} (100)`).join('\n')
    const result = decodeAos4TextRoster(`Faction\nFormation\n${units}\nGenerated by Listbot 4.0`)

    expect(result.parsedRoster).toBeUndefined()
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'input-too-large', severity: 'error' })
    )
  })

  it('decodes a Listbot text export from a roster file and rejects invalid UTF-8', async () => {
    const text = fixture('regiments.txt')
    const uploaded = await decodeAos4RosterFile({
      name: 'skaven-listbot.txt',
      bytes: new TextEncoder().encode(text),
    })
    const invalid = await decodeAos4RosterFile({
      name: 'invalid-listbot.txt',
      bytes: new Uint8Array([0xc3, 0x28]),
    })

    expect(uploaded.diagnostics).toEqual([])
    expect(uploaded.parsedRoster).toMatchObject({
      source: 'listbot-text',
      declaredFaction: 'Skaven',
      proposedName: "Skaven — Thanquol's Mutated Menagerie",
    })
    expect(invalid.parsedRoster).toBeUndefined()
    expect(invalid.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'unsafe-input', severity: 'error' })
    )
  })
})

/**
 * Listbot has no Regiments of Renown section: its game data files a regiment as a unit-shaped
 * entry (`isRor`), so the export writes the bundle exactly like a warscroll line. Resolution
 * falls back from warscrolls to the classified regiment groups only after every warscroll
 * attempt finds nothing (issue #1858), so a real warscroll sharing a regiment's name always
 * wins the unit line.
 */
describe('Listbot regiment-of-renown unit lines against the accepted corpus', () => {
  const resolveListbot = (text: string) => {
    const { parsedRoster } = decodeAos4TextRoster(text)
    if (!parsedRoster) throw new Error('the roster did not decode')
    return resolveParsedRoster(AOS4_CATALOG, parsedRoster, {
      defaultRulesContextId: AOS4_DEFAULT_RULES_CONTEXT_ID,
      createDocumentId: () => 'army:listbot-ror',
    })
  }
  const entityFor = (preview: ReturnType<typeof resolveListbot>, label: string) => {
    const match = preview.matches.find(candidate => candidate.label === label)
    return match && AOS4_CATALOG.entities.find(entity => entity.id === match.canonicalId)
  }

  it('resolves a regiment named on a plain unit line to the classified regiment group', () => {
    const preview = resolveListbot(
      [
        'Skaven',
        'Warpcog Convocation',
        '',
        '- 1 x Clanrats (150)',
        "- 1 x Lord Skaldior's Chosen (530)",
        '',
        '680/2000pts',
        '2 drops',
        '',
        'Generated by Listbot 4.0',
        '',
      ].join('\n')
    )

    expect(entityFor(preview, 'Clanrats')).toMatchObject({ kind: 'warscroll' })
    expect(entityFor(preview, "Lord Skaldior's Chosen")).toMatchObject({
      kind: 'content-group',
      groupType: 'regiment-of-renown',
    })
  })

  it('reads a shared name as the warscroll for its own faction and as the regiment elsewhere', () => {
    // Blades of the Hollow King is both a Soulblight Gravelords warscroll and a regiment three
    // other factions may include. The unit line means the unit where the unit is fieldable, and
    // the bought regiment where only the regiment is — never an ambiguity, never a guess.
    const roster = (faction: string, formation: string) =>
      [
        faction,
        formation,
        '',
        '- 1 x Blades of the Hollow King (260)',
        '',
        '260/2000pts',
        '1 drop',
        '',
        'Generated by Listbot 4.0',
        '',
      ].join('\n')

    const soulblight = resolveListbot(roster('Soulblight Gravelords', 'Deathrattle Legion'))
    expect(soulblight.diagnostics.filter(d => d.code === 'ambiguous-selection')).toEqual([])
    expect(entityFor(soulblight, 'Blades of the Hollow King')).toMatchObject({ kind: 'warscroll' })

    const nighthaunt = resolveListbot(roster('Nighthaunt', 'Procession of Death'))
    expect(nighthaunt.diagnostics.filter(d => d.code === 'ambiguous-selection')).toEqual([])
    expect(entityFor(nighthaunt, 'Blades of the Hollow King')).toMatchObject({
      kind: 'content-group',
      groupType: 'regiment-of-renown',
    })
  })

  it('fails closed with a named diagnostic when the regiment is not available to the faction', () => {
    // Sylvaneth is not on Lord Skaldior's inclusion list, so the line must surface a diagnostic
    // rather than resolve or silently drop.
    const preview = resolveListbot(
      [
        'Sylvaneth',
        'Lords of the Clan',
        '',
        "- 1 x Lord Skaldior's Chosen (530)",
        '',
        '530/2000pts',
        '1 drop',
        '',
        'Generated by Listbot 4.0',
        '',
      ].join('\n')
    )
    expect(entityFor(preview, "Lord Skaldior's Chosen")).toBeUndefined()
    expect(preview.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'inapplicable-selection',
        severity: 'warning',
        message: expect.stringContaining("Lord Skaldior's Chosen"),
      })
    )
  })
})
