// @vitest-environment jsdom

import ImportArmyModal from 'components/input/importArmy/importArmyModal'
import { useSubscriberAction } from 'components/input/importArmy/subscriberAction'
import { AOS4_CATALOG } from '../../aos4/generated'
import { MAX_ROSTER_FILE_BYTES } from '../../importers'
import { parseRosterXml, xmlToRosterJson } from 'tests/support/newRecruit'
import { render, unmountComponentAtNode } from 'tests/support/reactTestHelpers'
import { act } from 'react'
import { Simulate } from 'tests/support/reactTestHelpers'
import { MemoryRouter, Route, Routes } from 'react-router'
import { afterEach, beforeEach, describe, expect, it, type Mock, vi } from 'vitest'
import type { Aos4ArmyDocument } from '../../aos4/state'

const logRosterImport = vi.hoisted(() => vi.fn())
const auth = vi.hoisted(() => ({
  isAuthenticated: false,
  isLoading: false,
}))
const subscription = vi.hoisted(() => ({
  isActive: false,
  subscriptionLoading: false,
}))
const login = vi.hoisted(() => vi.fn())

vi.mock('utils/analytics', () => ({ logRosterImport }))

vi.mock('@auth0/auth0-react', () => ({
  useAuth0: () => auth,
}))

vi.mock('context/useSubscription', () => ({
  useSubscription: () => subscription,
}))

vi.mock('utils/hooks/useLogin', () => ({
  default: () => ({ isLoggingIn: false, login }),
}))

vi.mock('context/useTheme', () => ({
  useTheme: () => ({
    isDark: false,
    theme: {
      bgColor: 'bg-white',
      dropzone: 'dropzone',
      commitButton: 'btn btn-primary',
      genericButton: 'btn btn-outline-dark',
      text: 'text-dark',
    },
  }),
}))

vi.mock('components/modals/generic/generic_modal', () => ({
  default: ({ children, isOpen, label }: React.PropsWithChildren<{ isOpen: boolean; label: string }>) =>
    isOpen ? (
      <div aria-label={label} role="dialog">
        {children}
      </div>
    ) : null,
}))

const officialRoster = (unit = 'Annihilators', includeContext = true) => `Thunderhost 1000/1000 pts
Stormcast Eternals
Thunderhead Host
${includeContext ? "General's Handbook 2026-27" : ''}

REGIMENTS
Gardus Steel Soul (160)
${unit} (160)

Created with Warhammer Age of Sigmar: The App
App: 1.20.0 | Data: 345`

const rosterXml = `<?xml version="1.0" encoding="UTF-8"?>
<roster id="r1" name="Uploaded Stormhost" battleScribeVersion="2.03"
  gameSystemName="Age of Sigmar 4.0" xmlns="http://www.battlescribe.net/schema/rosterSchema">
  <forces>
    <force id="f1" name="General's Handbook 2026-27" catalogueName="Stormcast Eternals">
      <forces>
        <force id="f2" name="Regiment" catalogueName="Stormcast Eternals">
          <selections>
            <selection id="u1" name="Annihilators" number="1" type="unit" />
          </selections>
        </force>
      </forces>
    </force>
  </forces>
</roster>`

const listbotRoster = `Skaven
Thanquol's Mutated Menagerie

Regiment 1
Master Moulder (90)
[General]
[Warpstone Innards]
- 6 x Stormfiends (520)
[Doomflayer Gauntlets x2 ; Grinderfists x2]

Drops: 2
Total: 1000 / 1000
Generated by Listbot 4.0`

const findButton = (container: HTMLElement, label: string): HTMLButtonElement => {
  const button = Array.from(container.querySelectorAll('button')).find(
    candidate => candidate.textContent?.trim() === label
  )
  if (!button) throw new Error(`Button "${label}" not found`)
  return button
}

/**
 * `Simulate`'s event data type predates drag events and has no `dataTransfer`, so the dropped file
 * is attached through a cast rather than left untested.
 */
const dropEventData = (file: File): Parameters<typeof Simulate.drop>[1] =>
  ({ dataTransfer: { files: [file] } }) as unknown as Parameters<typeof Simulate.drop>[1]

const readBlobText = (blob: Blob): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onerror = () => reject(reader.error)
    reader.onload = () => resolve(String(reader.result))
    reader.readAsText(blob)
  })

const deferred = <T,>() => {
  let resolve!: (value: T) => void
  const promise = new Promise<T>(next => {
    resolve = next
  })
  return { promise, resolve }
}

const SubscriberActionHarness = ({ onAuthorized }: { onAuthorized: () => void }) => {
  const action = useSubscriberAction({
    featureName: 'My Armies',
    onAuthorized,
    origin: 'SubscriberActionTest',
  })
  return (
    <button disabled={action.disabled} onClick={action.run} type="button">
      Subscriber action
    </button>
  )
}

describe('subscriber-only account action', () => {
  let container: HTMLDivElement

  beforeEach(() => {
    auth.isAuthenticated = false
    auth.isLoading = false
    subscription.isActive = false
    subscription.subscriptionLoading = false
    login.mockReset()
    container = document.createElement('div')
    document.body.appendChild(container)
  })

  afterEach(() => {
    act(() => {
      unmountComponentAtNode(container)
    })
    container.remove()
  })

  it('opens login for signed-out users, Subscribe for inactive users, and paid actions for subscribers', () => {
    const onAuthorized = vi.fn()
    const renderHarness = () =>
      render(
        <MemoryRouter initialEntries={['/']}>
          <SubscriberActionHarness onAuthorized={onAuthorized} />
          <Routes>
            <Route path="/subscribe" element={<>Subscribe destination</>} />
          </Routes>
        </MemoryRouter>,
        container
      )

    act(() => {
      renderHarness()
    })
    act(() => {
      Simulate.click(container.querySelector('button')!)
    })
    expect(login).toHaveBeenCalledTimes(1)
    expect(onAuthorized).not.toHaveBeenCalled()

    auth.isAuthenticated = true
    act(() => {
      renderHarness()
    })
    act(() => {
      Simulate.click(container.querySelector('button')!)
    })
    expect(container.textContent).toContain('Subscribe destination')
    expect(onAuthorized).not.toHaveBeenCalled()

    act(() => {
      unmountComponentAtNode(container)
    })
    subscription.isActive = true
    act(() => {
      renderHarness()
    })
    act(() => {
      Simulate.click(container.querySelector('button')!)
    })
    expect(onAuthorized).toHaveBeenCalledTimes(1)
  })
})

describe('AoS 4 import modal', () => {
  let container: HTMLDivElement
  let onApply: Mock<(document: Aos4ArmyDocument) => void>
  let closeModal: Mock<() => void>

  const renderModal = () => {
    render(
      <ImportArmyModal
        closeModal={closeModal}
        createDocumentId={() => 'army:import-ui-test'}
        isOpen
        onApply={onApply}
      />,
      container
    )
  }

  const pasteAndPreview = (text: string) => {
    if (!container.querySelector('textarea')) {
      act(() => {
        Simulate.click(findButton(container, 'Paste roster'))
      })
    }
    const textarea = container.querySelector('textarea')!
    textarea.value = text
    act(() => {
      Simulate.change(textarea)
    })
    act(() => {
      Simulate.click(findButton(container, 'Preview import'))
    })
  }

  beforeEach(() => {
    onApply = vi.fn()
    closeModal = vi.fn()
    logRosterImport.mockReset()
    container = document.createElement('div')
    document.body.appendChild(container)
    act(() => {
      renderModal()
    })
  })

  afterEach(() => {
    act(() => {
      unmountComponentAtNode(container)
    })
    container.remove()
    vi.restoreAllMocks()
  })

  it('previews and atomically applies a supported pasted roster with a fresh local document', () => {
    pasteAndPreview(officialRoster())

    expect(container.textContent).toContain('Warhammer Age of Sigmar app')
    expect(container.textContent).toContain('Stormcast Eternals')
    expect(container.textContent).toContain('Thunderhead Host')
    expect(container.textContent).not.toContain('Send to devs')
    const apply = findButton(container, 'Import Army')
    expect(apply.disabled).toBe(false)

    act(() => {
      Simulate.click(apply)
    })

    expect(onApply).toHaveBeenCalledTimes(1)
    expect(onApply.mock.calls[0][0]).toMatchObject({
      id: 'army:import-ui-test',
      name: 'Thunderhost',
      reminderPreferences: {},
    })
    expect(onApply.mock.calls[0][0].explicitSelectionIds.length).toBeGreaterThan(1)
    expect(logRosterImport).toHaveBeenCalledWith({
      diagnosticCount: 0,
      outcome: 'success',
      selectionCount: 3,
      source: 'official-app-text',
    })
  })

  /*
   * Import is the main entry path — most rosters are built elsewhere — and until this pass its
   * three most prominent controls were all mis-weighted: Close was `modalDangerClass` (filled red
   * in dark theme, the loudest thing in the modal), Import Army was `modalSuccessClass` (white on
   * Bootstrap green at 3.13:1 in light theme, and merely outlined in dark), and Cancel was red
   * beside it.
   */
  it('weights close, cancel, and commit by what each one does', () => {
    const close = container.querySelector('button[aria-label="Close import"]')
    expect(close?.className).toContain('btn-close')
    expect(close?.className).not.toContain('btn-danger')

    expect(findButton(container, 'Cancel').className).toContain('btn-outline-dark')
    expect(findButton(container, 'Cancel').className).not.toContain('btn-danger')

    const apply = findButton(container, 'Import Army')
    expect(apply.className).toContain('btn-primary')
    expect(apply.className).not.toContain('btn-success')
  })

  /*
   * The selected source segment fills with Bootstrap's `.active` rather than `btn-info`, whose
   * white text measured 3.04:1 — and which read as a status rather than as the pressed state.
   */
  it('marks the selected import source with the pressed state, not a signal colour', () => {
    // The modal opens on the upload zone.
    expect(findButton(container, 'Upload roster').getAttribute('aria-pressed')).toBe('true')
    expect(findButton(container, 'Upload roster').className).toContain('active')
    expect(findButton(container, 'Upload roster').className).not.toContain('btn-info')
    expect(findButton(container, 'Paste roster').className).not.toContain('active')

    act(() => {
      Simulate.click(findButton(container, 'Paste roster'))
    })

    expect(findButton(container, 'Paste roster').className).toContain('active')
    expect(findButton(container, 'Upload roster').className).not.toContain('active')
  })

  it('opens a reproducible GitHub report and downloads the exact failed pasted roster', async () => {
    const pastedRoster = officialRoster().replace('Stormcast Eternals', 'Private Player Name')
    const createObjectUrl = vi.fn<(blob: Blob) => string>().mockReturnValue('blob:failed-import')
    const revokeObjectUrl = vi.fn()
    Object.defineProperties(URL, {
      createObjectURL: { configurable: true, value: createObjectUrl },
      revokeObjectURL: { configurable: true, value: revokeObjectUrl },
    })
    const downloaded: { href?: string; name?: string } = {}
    const downloadClick = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {
      const download = document.querySelector<HTMLAnchorElement>('a[download]')!
      downloaded.href = download.href
      downloaded.name = download.download
    })
    const openIssue = vi.spyOn(window, 'open').mockImplementation(() => null)

    pasteAndPreview(pastedRoster)

    expect(container.textContent).toContain('GitHub issues are public')
    expect(logRosterImport).toHaveBeenCalledWith({
      diagnosticCount: expect.any(Number),
      outcome: 'error',
      selectionCount: 3,
      source: 'official-app-text',
    })
    const report = findButton(container, 'Send to devs')
    act(() => {
      Simulate.click(report)
    })

    expect(createObjectUrl).toHaveBeenCalledTimes(1)
    const downloadedBlob = createObjectUrl.mock.calls[0][0] as Blob
    expect(await readBlobText(downloadedBlob)).toBe(pastedRoster)
    expect(downloaded).toEqual({
      href: 'blob:failed-import',
      name: 'aos-reminders-failed-import.txt',
    })
    expect(downloadClick).toHaveBeenCalledTimes(1)

    const issueUrl = new URL(openIssue.mock.calls[0][0] as string)
    expect(issueUrl.origin + issueUrl.pathname).toBe('https://github.com/daviseford/aos-reminders/issues/new')
    expect(issueUrl.searchParams.get('title')).toContain('Failed roster import')
    expect(issueUrl.searchParams.get('body')).toContain('aos-reminders-failed-import.txt')
    expect(issueUrl.searchParams.get('body')).toContain('missing-faction')
    expect(issueUrl.searchParams.get('body')).not.toContain(pastedRoster)
    expect(issueUrl.searchParams.get('body')).not.toContain('Private Player Name')

    await new Promise(resolve => setTimeout(resolve, 0))
    expect(revokeObjectUrl).toHaveBeenCalledWith('blob:failed-import')
  })

  /**
   * A name we cannot place is shown and skipped, not treated as a dead end. The player came from a
   * builder where the unit exists, so the useful outcome is the rest of the army plus a note about
   * what was dropped.
   */
  it('stays confirmable and reportable when a selection cannot be placed', () => {
    Object.defineProperties(URL, {
      createObjectURL: { configurable: true, value: vi.fn(() => 'blob:warning-import') },
      revokeObjectURL: { configurable: true, value: vi.fn() },
    })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined)
    const openIssue = vi.spyOn(window, 'open').mockImplementation(() => null)

    pasteAndPreview(officialRoster('Annihilators', false))

    expect(container.textContent).toContain('No rules context was declared')
    expect(findButton(container, 'Import Army').disabled).toBe(false)

    pasteAndPreview(officialRoster('Definitely Unknown Unit'))

    expect(container.textContent).toContain('Definitely Unknown Unit')
    expect(findButton(container, 'Import Army').disabled).toBe(false)

    act(() => {
      Simulate.click(findButton(container, 'Send to devs'))
    })

    const issueUrl = new URL(openIssue.mock.calls[0][0] as string)
    expect(issueUrl.searchParams.get('title')).toContain('warning')
    expect(issueUrl.searchParams.get('body')).toContain('imported this roster with warnings')
    expect(issueUrl.searchParams.get('body')).toContain('unknown-selection')

    act(() => {
      Simulate.click(findButton(container, 'Import Army'))
    })
    expect(onApply).toHaveBeenCalledTimes(1)
  })

  /**
   * The roster usually settles the ruleset itself, and asking anyway invites the player to change
   * an answer they never gave. The question appears only where one is genuinely missing.
   */
  it('asks which ruleset to use only when the roster declares none we carry', () => {
    pasteAndPreview(officialRoster())
    expect(container.querySelector('#import-rules-context')).toBeNull()

    pasteAndPreview(officialRoster('Annihilators', false))
    expect(container.textContent).toContain('Which ruleset do you want to use?')

    const select = container.querySelector<HTMLSelectElement>('#import-rules-context')!
    const spearhead = Array.from(select.options).find(option => option.textContent?.includes('Spearhead'))!
    select.value = spearhead.value
    act(() => {
      Simulate.change(select)
    })

    expect(container.querySelector<HTMLSelectElement>('#import-rules-context')!.value).toBe(spearhead.value)
    expect(container.textContent).toContain('Age of Sigmar Fourth Edition Spearhead')
  })

  /**
   * The #1979 roster: a GHB 2026-27 army carrying a battletome artefact. Under the replacement
   * model the dialog warned that the season replaced Seed of Rebirth and offered a ruleset
   * switch; the confirmed official reading ("Using the Scourge of Aqshy Rules": the seasonal
   * table is picked instead of others, not carried in addition — every table stays legal) keeps
   * battletome tables offered in season, so the same roster now imports without a caveat. The
   * dialog's switch-on-suggestion capability itself stays for future seasons' boundaries; with
   * no core-only content left in the accepted catalog there is nothing real to drive it with.
   */
  it('imports a seasonal roster carrying a battletome artefact without a caveat (#1979)', () => {
    pasteAndPreview(`Training 1000/1000 pts
Sylvaneth
Outcasts
General's Handbook 2026-27

General's Regiment
Branchwych (100)
• General
• Seed of Rebirth

Created with Warhammer Age of Sigmar: The App
App: 1.37.0 | Data: 476`)

    expect(container.textContent).not.toContain('has been replaced for the current season')
    expect(container.textContent).not.toContain('Seed of Rebirth" has been replaced')
    expect(findButton(container, 'Import Army').disabled).toBe(false)
  })

  /**
   * Uploading is the common path, so the modal opens on it — no click to switch modes here.
   */
  it('opens on the upload zone and previews a roster dropped onto it', async () => {
    const file = new File([rosterXml], 'stormhost.ros', { type: 'application/xml' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(rosterXml).buffer,
    })
    const dropzone = container.querySelector<HTMLDivElement>('.dropzone')!

    await act(async () => {
      Simulate.drop(dropzone, dropEventData(file))
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(container.textContent).toContain('stormhost.ros')
    expect(container.textContent).toContain('Uploaded Stormhost')
    expect(findButton(container, 'Import Army').disabled).toBe(false)
  })

  it('previews a native .ros upload locally', async () => {
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File([rosterXml], 'stormhost.ros', { type: 'application/xml' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(rosterXml).buffer,
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(container.textContent).toContain('New Recruit roster file')
    expect(container.textContent).toContain('Uploaded Stormhost')
    expect(findButton(container, 'Import Army').disabled).toBe(false)
  })

  /** New Recruit's third export reaches the same preview, through the same control. */
  it('previews a native .json upload locally', async () => {
    const rosterJson = JSON.stringify({ roster: xmlToRosterJson(parseRosterXml(rosterXml)) })
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File([rosterJson], 'stormhost.json', { type: 'application/json' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(rosterJson).buffer,
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(input.accept).toContain('.json')
    expect(container.textContent).toContain('stormhost.json')
    expect(container.textContent).toContain('New Recruit roster file')
    expect(container.textContent).toContain('Uploaded Stormhost')
    expect(findButton(container, 'Import Army').disabled).toBe(false)
  })

  it('uploads a Listbot text file and applies its canonical composition', async () => {
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File([listbotRoster], 'skaven-listbot.txt', { type: 'text/plain' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(listbotRoster).buffer,
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
      await Promise.resolve()
    })

    expect(input.accept).toContain('.txt')
    expect(input.accept).toContain('.json')
    expect(container.textContent).toContain('Listbot 4.0')
    expect(findButton(container, 'Import Army').disabled).toBe(false)

    act(() => {
      Simulate.click(findButton(container, 'Import Army'))
    })
    const imported = onApply.mock.calls[0][0]
    const entityById = new Map(AOS4_CATALOG.entities.map(entity => [entity.id, entity]))
    const importedNames = imported.explicitSelectionIds.map(id => entityById.get(id)?.name)
    expect(importedNames).toEqual(
      expect.arrayContaining(['Skaven', 'Master Moulder', 'Stormfiends', 'WARPSTONE INNARDS'])
    )
  })

  it('rejects an oversized roster before reading it into browser memory', async () => {
    act(() => {
      Simulate.click(findButton(container, 'Upload roster'))
    })
    const file = new File(['oversized'], 'oversized-listbot.txt', { type: 'text/plain' })
    const arrayBuffer = vi.fn(async () => new ArrayBuffer(0))
    Object.defineProperties(file, {
      arrayBuffer: { value: arrayBuffer },
      size: { value: MAX_ROSTER_FILE_BYTES + 1 },
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
    })

    expect(arrayBuffer).not.toHaveBeenCalled()
    expect(container.textContent).toContain(`Roster files must be ${MAX_ROSTER_FILE_BYTES} bytes or smaller.`)
    expect(findButton(container, 'Import Army').disabled).toBe(true)
  })

  it('downloads an exact GitHub-compatible copy of a failed .rosz upload', async () => {
    const rosterBytes = new Uint8Array([0x50, 0x4b, 0x03])
    const file = new File([rosterBytes], 'private-player-name.rosz', { type: 'application/zip' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => rosterBytes.buffer,
    })
    const createObjectUrl = vi.fn<(blob: Blob) => string>().mockReturnValue('blob:failed-rosz')
    Object.defineProperties(URL, {
      createObjectURL: { configurable: true, value: createObjectUrl },
      revokeObjectURL: { configurable: true, value: vi.fn() },
    })
    const downloaded: { name?: string } = {}
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {
      downloaded.name = document.querySelector<HTMLAnchorElement>('a[download]')!.download
    })
    const openIssue = vi.spyOn(window, 'open').mockImplementation(() => null)
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await Promise.resolve()
      await Promise.resolve()
    })
    expect(container.textContent).toContain('not a valid ZIP archive')

    act(() => {
      Simulate.click(findButton(container, 'Send to devs'))
    })

    expect(createObjectUrl).toHaveBeenCalledWith(file)
    expect(downloaded.name).toBe('aos-reminders-failed-import.rosz.zip')
    const issueUrl = new URL(openIssue.mock.calls[0][0] as string)
    expect(issueUrl.searchParams.get('title')).not.toContain('private-player-name')
    expect(issueUrl.searchParams.get('body')).not.toContain('private-player-name')
    expect(issueUrl.searchParams.get('body')).toContain('aos-reminders-failed-import.rosz.zip')
    expect(issueUrl.searchParams.get('body')).toContain('unsafe-input')
  })

  /**
   * A `.json` upload is now read rather than turned away by its extension, so this fails on
   * content — a JSON file that is not a New Recruit roster — and is still reportable with the
   * exact bytes, without leaking what was in the list.
   */
  it('allows a failed JSON upload to be reported with its exact bytes', async () => {
    const rosterJson = '{"name":"Private JSON Roster"}'
    const file = new File([rosterJson], 'private-roster.json', { type: 'application/json' })
    Object.defineProperty(file, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(rosterJson).buffer,
    })
    const createObjectUrl = vi.fn<(blob: Blob) => string>().mockReturnValue('blob:failed-json')
    Object.defineProperties(URL, {
      createObjectURL: { configurable: true, value: createObjectUrl },
      revokeObjectURL: { configurable: true, value: vi.fn() },
    })
    const downloaded: { name?: string } = {}
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {
      downloaded.name = document.querySelector<HTMLAnchorElement>('a[download]')!.download
    })
    const openIssue = vi.spyOn(window, 'open').mockImplementation(() => null)
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!
    Object.defineProperty(input, 'files', { configurable: true, value: [file] })

    await act(async () => {
      Simulate.change(input)
      await new Promise(resolve => setTimeout(resolve, 0))
    })
    expect(container.textContent).toContain('exactly one supported roster JSON root')

    act(() => {
      Simulate.click(findButton(container, 'Send to devs'))
    })

    expect(createObjectUrl).toHaveBeenCalledWith(file)
    expect(downloaded.name).toBe('aos-reminders-failed-import.json')
    const issueUrl = new URL(openIssue.mock.calls[0][0] as string)
    expect(issueUrl.searchParams.get('body')).toContain('unsafe-input')
    expect(issueUrl.searchParams.get('body')).not.toContain('private-roster')
    expect(issueUrl.searchParams.get('body')).not.toContain('Private JSON Roster')
  })

  it('keeps the report file paired with the latest upload when reads finish out of order', async () => {
    const firstRead = deferred<ArrayBuffer>()
    const firstFile = new File([''], 'first.rosz', { type: 'application/zip' })
    Object.defineProperty(firstFile, 'arrayBuffer', {
      value: () => firstRead.promise,
    })
    const secondText = 'This is the latest unsupported roster.'
    const secondFile = new File([secondText], 'latest.txt', { type: 'text/plain' })
    Object.defineProperty(secondFile, 'arrayBuffer', {
      value: async () => new TextEncoder().encode(secondText).buffer,
    })
    const input = container.querySelector<HTMLInputElement>('input[type="file"]')!

    Object.defineProperty(input, 'files', { configurable: true, value: [firstFile] })
    act(() => {
      Simulate.change(input)
    })

    Object.defineProperty(input, 'files', { configurable: true, value: [secondFile] })
    await act(async () => {
      Simulate.change(input)
      await new Promise(resolve => setTimeout(resolve, 0))
    })
    expect(container.textContent).toContain(
      'not a supported current official app, Listbot 4.0, or Sigdex export'
    )

    await act(async () => {
      firstRead.resolve(new Uint8Array([0x50, 0x4b, 0x03]).buffer)
      await new Promise(resolve => setTimeout(resolve, 0))
    })

    expect(container.textContent).toContain(
      'not a supported current official app, Listbot 4.0, or Sigdex export'
    )
    expect(container.textContent).not.toContain('not a valid ZIP archive')

    const createObjectUrl = vi.fn<(blob: Blob) => string>().mockReturnValue('blob:latest-import')
    Object.defineProperties(URL, {
      createObjectURL: { configurable: true, value: createObjectUrl },
      revokeObjectURL: { configurable: true, value: vi.fn() },
    })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined)
    const openIssue = vi.spyOn(window, 'open').mockImplementation(() => null)

    act(() => {
      Simulate.click(findButton(container, 'Send to devs'))
    })

    expect(createObjectUrl).toHaveBeenCalledWith(secondFile)
    const issueUrl = new URL(openIssue.mock.calls[0][0] as string)
    expect(issueUrl.searchParams.get('body')).toContain('unsupported-source')
    expect(issueUrl.searchParams.get('body')).not.toContain('unsafe-input')
  })

  it('cancels without applying or persisting the raw roster', () => {
    pasteAndPreview(officialRoster())
    act(() => {
      Simulate.click(findButton(container, 'Cancel'))
    })

    expect(closeModal).toHaveBeenCalledTimes(1)
    expect(onApply).not.toHaveBeenCalled()
  })
})
