import { readFileSync } from 'node:fs'
import path from 'node:path'
import { canonicalOfficialProfileName } from '../../aos4/generate'
import { AOS4_RUNTIME_PROJECTION } from '../../aos4/generated'
import { canonicalNameKey, foldUnicodeName, normalizedNameText } from '../../aos4/normalize'
import {
  DEFAULT_OFFICIAL_NAMING_DISCREPANCIES_PATH,
  parseOfficialNamingDiscrepancyLedger,
  parseOfficialProfileSweepArguments,
  sweepOfficialRosterOptions,
  type OfficialNamingDiscrepancy,
  type OfficialProfileSweepRecord,
} from '../../aos4/review'

interface OfficialBattleProfileLedger {
  records: Array<
    OfficialProfileSweepRecord & {
      fact: { kind: 'unit' | 'roster-option' | 'regiment-of-renown'; name: string }
    }
  >
}

const ledger = JSON.parse(
  readFileSync(path.join(process.cwd(), 'data', 'aos4', 'catalog', 'official-battle-profiles.json'), 'utf8')
) as OfficialBattleProfileLedger

const reviewedDiscrepancies = parseOfficialNamingDiscrepancyLedger(
  JSON.parse(
    readFileSync(path.join(process.cwd(), DEFAULT_OFFICIAL_NAMING_DISCREPANCIES_PATH), 'utf8')
  ) as unknown
).discrepancies

const allRealNames = [
  ...ledger.records.map(record => record.fact.name),
  ...AOS4_RUNTIME_PROJECTION.entities.map(entity => entity.name),
]

const necrisDiscrepancy: OfficialNamingDiscrepancy = {
  faction: 'Ossiarch Bonereapers',
  context: 'standard',
  officialName: 'Shard of the Necris',
  runtimeName: 'SHARD OF NECRIS',
  reason: 'GW-vs-Wahapedia wording difference preserved per issue #1851.',
  recordedAt: '2026-08-02',
}

const rosterOption = (
  name: string,
  overrides: Partial<OfficialProfileSweepRecord['fact']> = {},
  status: OfficialProfileSweepRecord['status'] = 'effective'
): OfficialProfileSweepRecord => ({
  status,
  fact: {
    kind: 'roster-option',
    name,
    faction: 'Stormcast Eternals',
    context: 'standard',
    optionType: 'Artefact of Power',
    page: 1,
    row: 1,
    ...overrides,
  },
})

describe('shared Unicode-hardened name key', () => {
  // The #1851 exemplars, spelled exactly as the official Battle Profiles ledger and the runtime
  // carry them. The left/right pairs differ by U+2011 non-breaking hyphens, U+2018/U+2019 curly
  // quotes, and case - the variants the ad hoc sweep's lowercase matcher failed to fold.
  const exemplars: Array<[official: string, runtime: string]> = [
    ['Heat-seeking Auto-endrin', 'HEAT-SEEKING AUTO‑ENDRIN'], // runtime hyphen is U+2011
    ['Dawner’s Triumph', 'Dawners Triumph'],
    ['‘Fire, You Worms!’', '’FIRE, YOU WORMS!’'],
    ['Hegsson Solutions ‘Old Reliable’ Hullplates', 'HEGSSON SOLUTIONS ’OLD RELIABLE’ HULLPLATES'],
  ]

  it('folds the #1851 exemplar variants onto one key', () => {
    exemplars.forEach(([official, runtime]) => {
      expect(canonicalNameKey(official)).toBe(canonicalNameKey(runtime))
    })
  })

  it('folds the variants the naive lowercase comparison missed', () => {
    // The regression class: lowercase+trim comparison misses every exemplar pair the hardened
    // key matches, because it never folds U+2011 hyphens or curly quotes.
    exemplars.forEach(([official, runtime]) => {
      expect(official.trim().toLowerCase()).not.toBe(runtime.trim().toLowerCase())
    })
  })

  it('folds dash variants, quote variants, and combining marks explicitly', () => {
    expect(foldUnicodeName('AUTO‑ENDRIN')).toBe('auto-endrin') // U+2011 non-breaking hyphen
    expect(foldUnicodeName('AUTO–ENDRIN')).toBe('auto-endrin') // U+2013 en dash
    expect(foldUnicodeName('AUTO—ENDRIN')).toBe('auto-endrin') // U+2014 em dash
    expect(foldUnicodeName('Dawner’s')).toBe("dawner's") // U+2019 right single quote
    expect(foldUnicodeName('‘quoted’')).toBe("'quoted'")
    expect(foldUnicodeName('“quoted”')).toBe('"quoted"')
    expect(foldUnicodeName('Café')).toBe('cafe') // composed e-acute, decomposed by NFKD
    expect(foldUnicodeName('Café')).toBe('cafe') // pre-decomposed combining acute
  })

  it('keeps parenthetical wording variants distinct beyond their punctuation', () => {
    // Parentheses fold away, but the word they wrap does not: the official "Shard of the Necris"
    // stays distinct from the runtime "SHARD OF NECRIS", which is a genuine GW-vs-Wahapedia
    // naming discrepancy (#1851), never a matcher artifact.
    expect(canonicalNameKey('Shard of (the) Necris')).toBe(canonicalNameKey('Shard of the Necris'))
    expect(canonicalNameKey('Shard of the Necris')).not.toBe(canonicalNameKey('SHARD OF NECRIS'))
  })

  it('preserves word boundaries in the reconciliation comparison form', () => {
    expect(normalizedNameText('Dawner’s Triumph')).toBe('dawner s triumph')
    expect(normalizedNameText('HEAT-SEEKING AUTO‑ENDRIN')).toBe('heat seeking auto endrin')
  })

  it('produces the exact key the historical canonicalOfficialProfileName produced', () => {
    // The reviewed regiment-of-renown dispositions in the checked-in ledger were generated by the
    // pre-#1875 inline implementation. The shared key must reproduce it byte-for-byte across
    // every real official name and runtime entity name, or dispositions could shift without a
    // corpus review.
    const historical = (value: string): string =>
      value
        .normalize('NFKD')
        .replace(/[‘’']/g, '')
        .replace(/[^a-z0-9]+/gi, '')
        .toLowerCase()
    expect(allRealNames.length).toBeGreaterThan(1000)
    allRealNames.forEach(name => {
      expect(canonicalOfficialProfileName(name)).toBe(historical(name))
      expect(canonicalNameKey(name)).toBe(historical(name))
    })
  })

  it('produces the exact text the historical reconciliation normalizeName produced', () => {
    // The reconciliation linker's normalizeName now delegates to normalizedNameText. The linker
    // decides which candidate facts join which entities, so its comparison form must reproduce
    // the pre-#1875 inline implementation byte-for-byte across every real name, or
    // reconciliation matching - and therefore the generated corpus - could shift without a
    // corpus review.
    const combiningMarks = new RegExp(`[${String.fromCharCode(0x0300)}-${String.fromCharCode(0x036f)}]`, 'g')
    const historical = (value: string): string =>
      value
        .normalize('NFKD')
        .replace(combiningMarks, '')
        .replace(/[’‘]/g, "'")
        .replace(/[^a-z0-9]+/gi, ' ')
        .trim()
        .toLocaleLowerCase('en')
    expect(allRealNames.length).toBeGreaterThan(1000)
    allRealNames.forEach(name => {
      expect(normalizedNameText(name)).toBe(historical(name))
    })
  })
})

describe('official naming-discrepancy ledger', () => {
  it('carries the reviewed Shard of the Necris ruling with full traceability', () => {
    expect(reviewedDiscrepancies).toEqual([
      expect.objectContaining({
        faction: 'Ossiarch Bonereapers',
        context: 'standard',
        officialName: 'Shard of the Necris',
        runtimeName: 'SHARD OF NECRIS',
        reason: expect.stringContaining('#1851'),
        recordedAt: expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/),
      }),
    ])
  })

  it('rejects a malformed ledger', () => {
    expect(() => parseOfficialNamingDiscrepancyLedger({ schemaVersion: 2, discrepancies: [] })).toThrow(
      /incompatible schema/
    )
    expect(() =>
      parseOfficialNamingDiscrepancyLedger({
        schemaVersion: 1,
        discrepancies: [{ ...necrisDiscrepancy, recordedAt: 'yesterday' }],
      })
    ).toThrow(/malformed/)
    expect(() =>
      parseOfficialNamingDiscrepancyLedger({
        schemaVersion: 1,
        discrepancies: [{ ...necrisDiscrepancy, faction: ' ' }],
      })
    ).toThrow(/malformed/)
  })
})

describe('official-profile sweep', () => {
  const runtime = [{ name: 'HEAT-SEEKING AUTO‑ENDRIN' }, { name: 'SHARD OF NECRIS' }]

  it('matches Unicode spelling variants instead of reporting them absent', () => {
    const result = sweepOfficialRosterOptions([rosterOption('Heat-seeking Auto-endrin')], runtime, [])
    expect(result).toMatchObject({
      rosterOptionRecords: 1,
      comparedRosterOptions: 1,
      matchedByName: 1,
      matchedByReviewedDiscrepancy: 0,
      findings: [],
    })
  })

  it('reports a genuinely absent roster option', () => {
    const result = sweepOfficialRosterOptions([rosterOption('Utterly Missing Option')], runtime, [])
    expect(result.findings).toEqual([
      expect.objectContaining({ code: 'unmatched-roster-option', name: 'Utterly Missing Option' }),
    ])
  })

  it('never requires a superseded row in runtime', () => {
    const result = sweepOfficialRosterOptions([rosterOption('Retired Option', {}, 'superseded')], runtime, [])
    expect(result).toMatchObject({ rosterOptionRecords: 1, comparedRosterOptions: 0, findings: [] })
  })

  it('accepts a reviewed naming discrepancy without hiding its distinct names', () => {
    const result = sweepOfficialRosterOptions(
      [rosterOption('Shard of the Necris', { faction: 'Ossiarch Bonereapers' })],
      runtime,
      [necrisDiscrepancy]
    )
    expect(result).toMatchObject({ matchedByName: 0, matchedByReviewedDiscrepancy: 1, findings: [] })
  })

  it('scopes a naming discrepancy to its own faction and context', () => {
    // A future same-named option in another faction or context must never be silently absorbed
    // by an unrelated reviewed entry.
    const otherFaction = sweepOfficialRosterOptions(
      [rosterOption('Shard of the Necris', { faction: 'Stormcast Eternals' })],
      runtime,
      [necrisDiscrepancy]
    )
    expect(otherFaction.findings).toEqual([
      expect.objectContaining({ code: 'unmatched-roster-option', name: 'Shard of the Necris' }),
    ])
    const otherContext = sweepOfficialRosterOptions(
      [rosterOption('Shard of the Necris', { faction: 'Ossiarch Bonereapers', context: 'seasonal' })],
      runtime,
      [necrisDiscrepancy]
    )
    expect(otherContext.findings).toEqual([
      expect.objectContaining({ code: 'unmatched-roster-option', context: 'seasonal' }),
    ])
  })

  it('reports a stale naming discrepancy whose runtime name vanished', () => {
    const result = sweepOfficialRosterOptions([], [{ name: 'HEAT-SEEKING AUTO‑ENDRIN' }], [necrisDiscrepancy])
    expect(result.findings).toEqual([
      expect.objectContaining({ code: 'stale-naming-discrepancy', officialName: 'Shard of the Necris' }),
    ])
  })

  it('reports a resolved naming discrepancy once the official name matches directly', () => {
    const result = sweepOfficialRosterOptions(
      [],
      [{ name: 'Shard of the Necris' }, ...runtime],
      [necrisDiscrepancy]
    )
    expect(result.findings).toEqual([
      expect.objectContaining({
        code: 'stale-naming-discrepancy',
        message: expect.stringContaining('now matches the runtime directly'),
      }),
    ])
  })

  it('guards against two distinct official options collapsing onto one key', () => {
    const result = sweepOfficialRosterOptions(
      [rosterOption('Droth-helm'), rosterOption('Droth’helm')],
      [{ name: 'DROTH-HELM' }],
      []
    )
    expect(result.findings).toEqual([
      expect.objectContaining({
        code: 'conflated-official-options',
        names: ['Droth-helm', 'Droth’helm'],
      }),
    ])
  })

  it('finds zero false findings across the full checked-in ledger and runtime', () => {
    // The re-run of #1851's 307-option sweep with the hardened matcher: every effective
    // officially-established roster option matches the runtime, with exactly one reviewed
    // naming discrepancy (Shard of the Necris) and no collisions.
    const result = sweepOfficialRosterOptions(
      ledger.records,
      AOS4_RUNTIME_PROJECTION.entities,
      reviewedDiscrepancies
    )
    expect(result).toEqual({
      rosterOptionRecords: 307,
      comparedRosterOptions: 287,
      matchedByName: 286,
      matchedByReviewedDiscrepancy: 1,
      findings: [],
    })
  })

  it('still matches every #1851 false-negative name in the real data', () => {
    const findingsFor = (name: string) => {
      const rows = ledger.records.filter(
        record => record.fact.kind === 'roster-option' && record.fact.name === name
      )
      expect(rows.length).toBeGreaterThan(0)
      return sweepOfficialRosterOptions(rows, AOS4_RUNTIME_PROJECTION.entities, reviewedDiscrepancies)
        .findings
    }
    expect(findingsFor('Heat-seeking Auto-endrin')).toEqual([])
    expect(findingsFor('Dawner’s Triumph')).toEqual([])
    expect(findingsFor('‘Fire, You Worms!’')).toEqual([])
    expect(findingsFor('Hegsson Solutions ‘Old Reliable’ Hullplates')).toEqual([])
    expect(findingsFor('Shard of the Necris')).toEqual([])
  })
})

describe('official-profile sweep command', () => {
  it('parses defaults and overrides', () => {
    expect(parseOfficialProfileSweepArguments([])).toEqual({
      officialProfilesPath: path.join('data', 'aos4', 'catalog', 'official-battle-profiles.json'),
      runtimePath: path.join('src', 'aos4', 'generated', 'corpus', 'runtime.json'),
      discrepanciesPath: DEFAULT_OFFICIAL_NAMING_DISCREPANCIES_PATH,
    })
    expect(
      parseOfficialProfileSweepArguments([
        '--official-battle-profiles',
        'ledger.json',
        '--runtime',
        'runtime.json',
        '--naming-discrepancies',
        'discrepancies.json',
      ])
    ).toEqual({
      officialProfilesPath: 'ledger.json',
      runtimePath: 'runtime.json',
      discrepanciesPath: 'discrepancies.json',
    })
    expect(() => parseOfficialProfileSweepArguments(['--runtime'])).toThrow(/requires a value/)
    expect(() => parseOfficialProfileSweepArguments(['--bogus'])).toThrow(/Unknown argument/)
  })
})
