// @vitest-environment jsdom

import { describe, expect, it } from 'vitest'
import { createAos4PrintDocument, type PrintReminderInput } from '../../aos4/print'

const reminder = (overrides: Partial<PrintReminderInput> & { id: string }): PrintReminderInput => ({
  name: `Rule ${overrides.id}`,
  windowKey: 'hero-phase',
  windowLabel: 'Hero Phase',
  typeLabel: 'Active · Your turn',
  effect: `Effect for ${overrides.id}`,
  hidden: false,
  ...overrides,
})

describe('createAos4PrintDocument', () => {
  it('omits hidden reminders', () => {
    const document = createAos4PrintDocument(
      [reminder({ id: 'a' }), reminder({ id: 'b', hidden: true }), reminder({ id: 'c' })],
      { armyName: 'Test Army', factionName: 'Stormcast Eternals' }
    )

    const ids = document.sections.flatMap(section => section.rules.map(rule => rule.id))
    expect(ids).toEqual(['a', 'c'])
  })

  it('drops a section that contains only hidden reminders', () => {
    const document = createAos4PrintDocument(
      [
        reminder({ id: 'a' }),
        reminder({ id: 'b', windowKey: 'movement-phase', windowLabel: 'Movement Phase', hidden: true }),
      ],
      { armyName: 'Test Army', factionName: 'Stormcast Eternals' }
    )

    expect(document.sections.map(section => section.key)).toEqual(['hero-phase'])
  })

  it('groups by window and preserves the incoming reminder order', () => {
    const document = createAos4PrintDocument(
      [
        reminder({ id: 'hero-2' }),
        reminder({ id: 'hero-1' }),
        reminder({ id: 'move-1', windowKey: 'movement-phase', windowLabel: 'Movement Phase' }),
      ],
      { armyName: 'Test Army', factionName: 'Stormcast Eternals' }
    )

    expect(document.sections.map(section => section.heading)).toEqual(['Hero Phase', 'Movement Phase'])
    expect(document.sections[0].rules.map(rule => rule.id)).toEqual(['hero-2', 'hero-1'])
  })

  it('renders trigger, declare, effect and note as labelled paragraphs in reading order', () => {
    const document = createAos4PrintDocument(
      [
        reminder({
          id: 'a',
          reactionTrigger: 'An enemy unit ends a charge move',
          declare: 'Pick a friendly unit',
          effect: 'Roll a dice',
          note: 'Remember the mount trait',
        }),
      ],
      { armyName: 'Test Army', factionName: 'Stormcast Eternals' }
    )

    expect(document.sections[0].rules[0].paragraphs).toEqual([
      { role: 'ruleBody', label: 'Trigger', text: 'An enemy unit ends a charge move' },
      { role: 'ruleBody', label: 'Declare', text: 'Pick a friendly unit' },
      { role: 'ruleBody', label: 'Effect', text: 'Roll a dice' },
      { role: 'ruleNote', label: 'Note', text: 'Remember the mount trait' },
    ])
  })

  it('titles a rule with its timing label so the PDF matches the on-screen entry', () => {
    const document = createAos4PrintDocument(
      [reminder({ id: 'a', name: 'Sigmarite Thundershield', typeLabel: 'Passive' })],
      { armyName: 'Test Army', factionName: 'Stormcast Eternals' }
    )

    expect(document.sections[0].rules[0].title).toBe('Passive - Sigmarite Thundershield')
  })

  it('builds the army summary from selected warscrolls with points', () => {
    const document = createAos4PrintDocument([reminder({ id: 'a' })], {
      armyName: 'Hammers of Sigmar',
      factionName: 'Stormcast Eternals',
      warscrolls: [
        { name: 'Liberators', profile: { points: 110, unitSize: 5 } },
        { name: 'Lord-Imperatant', profile: { points: 150, unitSize: 1 } },
        { name: 'Profile-Only Thing', profile: { unitSize: 3 } },
        { name: 'Unpointed Thing' },
      ],
    })

    expect(document.title).toBe('Hammers of Sigmar')
    expect(document.subtitle).toBe('Stormcast Eternals')
    expect(document.summary?.lines).toEqual([
      'Liberators (5) - 110 pts',
      'Lord-Imperatant (1) - 150 pts',
      'Profile-Only Thing (3)',
      'Unpointed Thing',
    ])
    expect(document.summary?.heading).toBe('Hammers of Sigmar - 260 pts')
  })

  it('omits the subtitle when the army name is just the faction name', () => {
    const document = createAos4PrintDocument([reminder({ id: 'a' })], {
      armyName: 'Stormcast Eternals',
      factionName: 'Stormcast Eternals',
    })

    expect(document.subtitle).toBeUndefined()
  })

  it('always carries the attribution footer', () => {
    const document = createAos4PrintDocument([reminder({ id: 'a' })], {
      armyName: 'Test Army',
      factionName: 'Stormcast Eternals',
    })

    expect(document.footer).toEqual(['Generated by AoS Reminders', 'aosreminders.com'])
  })
})
