/**
 * Builds the New Recruit fixture manifest.
 *
 * The manifest is generated, never hand-maintained: it indexes every captured list, records
 * checksums and sizes, and aggregates which coverage shapes the corpus actually exercises.
 * `importFixtures.test.ts` regenerates it in memory and fails if the committed copy has drifted,
 * so adding a fixture without regenerating is caught in CI.
 *
 * Regenerate with: yarn fixtures:new-recruit
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'

export const FIXTURE_ROOT = path.resolve(process.cwd(), 'src/tests/fixtures/aos4/import/new-recruit')
export const LISTS_ROOT = path.join(FIXTURE_ROOT, 'lists')
export const MANIFEST_PATH = path.join(FIXTURE_ROOT, 'manifest.json')

export const FORMATS = ['ros', 'rosz', 'json'] as const
export type Format = (typeof FORMATS)[number]

export interface ManifestFile {
  bytes: number
  sha256: string
}

export interface ManifestList {
  id: string
  faction: string
  rulesContext: string
  pointsLimit: number
  legalForPlay: boolean
  shapes: string[]
  files: Record<Format, ManifestFile>
}

export interface Manifest {
  schemaVersion: 1
  note: string
  lists: ManifestList[]
  coverage: Record<string, string[]>
  totals: {
    lists: number
    bytes: Record<Format, number>
    shapes: number
  }
}

const digest = (file: string): ManifestFile => {
  const contents = readFileSync(file)
  return {
    bytes: statSync(file).size,
    sha256: createHash('sha256').update(contents).digest('hex'),
  }
}

export const listDirectories = (): string[] => {
  try {
    return readdirSync(LISTS_ROOT, { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => entry.name)
      .sort((left, right) => left.localeCompare(right))
  } catch {
    return []
  }
}

export const buildManifest = (): Manifest => {
  const lists: ManifestList[] = listDirectories().map(id => {
    const directory = path.join(LISTS_ROOT, id)
    const meta = JSON.parse(readFileSync(path.join(directory, 'meta.json'), 'utf8'))
    if (meta.id !== id) {
      throw new Error(`meta.json id "${meta.id}" does not match directory "${id}"`)
    }

    const files = Object.fromEntries(
      FORMATS.map(format => [format, digest(path.join(directory, `list.${format}`))])
    ) as Record<Format, ManifestFile>

    return {
      id,
      faction: meta.faction,
      rulesContext: meta.rulesContext,
      pointsLimit: meta.pointsLimit,
      legalForPlay: meta.legality?.legalForPlay ?? true,
      shapes: [...(meta.shapes ?? [])].sort((left: string, right: string) => left.localeCompare(right)),
      files,
    }
  })

  const coverage: Record<string, string[]> = {}
  for (const list of lists) {
    for (const shape of list.shapes) {
      coverage[shape] = [...(coverage[shape] ?? []), list.id]
    }
  }

  const bytes = Object.fromEntries(
    FORMATS.map(format => [format, lists.reduce((sum, list) => sum + list.files[format].bytes, 0)])
  ) as Record<Format, number>

  return {
    schemaVersion: 1,
    note: 'Generated by src/tests/support/newRecruitManifest.ts. Do not edit by hand — run `yarn fixtures:new-recruit`.',
    lists,
    coverage: Object.fromEntries(
      Object.entries(coverage).sort(([left], [right]) => left.localeCompare(right))
    ),
    totals: {
      lists: lists.length,
      bytes,
      shapes: Object.keys(coverage).length,
    },
  }
}

export const serializeManifest = (manifest: Manifest): string => `${JSON.stringify(manifest, null, 2)}\n`

export const writeManifest = (): Manifest => {
  const manifest = buildManifest()
  writeFileSync(MANIFEST_PATH, serializeManifest(manifest), 'utf8')
  return manifest
}
