// This file is used for data re-used across any army.
// As well as core rules that are broader in scope
export { default as GenericArtifacts } from './artifacts'
export { default as GenericCommandAbilities } from './command_abilities'
export { default as GenericCommandTraits } from './command_traits'
export { default as CoreBattalions } from './core_battalions'
export { default as CoreRules } from './core_rules'
export { default as GenericEffects } from './effects'
export { default as GenericEndlessSpells } from './endless_spells'
export { default as GenericGrandStrategies } from './grand_strategies'
export { default as GenericIncarnates } from './incarnates'
export { default as GenericMonstrousRampages } from './monstrous_rampages'
export { default as GenericPrayers } from './prayers'
export { default as Realmscapes } from './realmscapes'
export { default as GenericScenery } from './scenery'
export { default as GenericSpells } from './spells'
export { default as GenericTriumphs } from './triumphs'
