import type { PrintDocument, PrintParagraph, PrintRule, PrintSection } from './types'

/**
 * Structural subset of `Aos4ReminderViewModel`. Declared here so the print model does not depend on
 * the view layer and can be exercised with plain fixtures.
 */
export interface PrintReminderInput {
  id: string
  name: string
  windowKey: string
  windowLabel: string
  typeLabel: string
  declare?: string
  reactionTrigger?: string
  effect: string
  hidden: boolean
  note?: string
}

export interface PrintWarscrollInput {
  name: string
  profile?: {
    points: number
    unitSize: number
  }
}

export interface PrintArmyInput {
  armyName: string
  factionName: string
  warscrolls?: PrintWarscrollInput[]
}

/** Wrapping reproduces text by joining on single spaces, so collapse runs of whitespace up front. */
const normalize = (value: string): string => value.replace(/\s+/g, ' ').trim()

const paragraphs = (reminder: PrintReminderInput): PrintParagraph[] => [
  ...(reminder.reactionTrigger
    ? [{ role: 'ruleBody' as const, label: 'Trigger', text: normalize(reminder.reactionTrigger) }]
    : []),
  ...(reminder.declare
    ? [{ role: 'ruleBody' as const, label: 'Declare', text: normalize(reminder.declare) }]
    : []),
  { role: 'ruleBody' as const, label: 'Effect', text: normalize(reminder.effect) },
  ...(reminder.note ? [{ role: 'ruleNote' as const, label: 'Note', text: normalize(reminder.note) }] : []),
]

const toRule = (reminder: PrintReminderInput): PrintRule => ({
  id: reminder.id,
  title: reminder.typeLabel ? `${reminder.typeLabel} - ${reminder.name}` : reminder.name,
  paragraphs: paragraphs(reminder),
})

const summaryLine = (warscroll: PrintWarscrollInput): string =>
  warscroll.profile
    ? `${warscroll.name} (${warscroll.profile.unitSize}) - ${warscroll.profile.points} pts`
    : warscroll.name

const buildSummary = (army: PrintArmyInput) => {
  const warscrolls = army.warscrolls ?? []
  if (!warscrolls.length) return undefined

  const points = warscrolls.reduce((total, warscroll) => total + (warscroll.profile?.points ?? 0), 0)
  return {
    heading: points ? `${army.armyName} - ${points} pts` : army.armyName,
    lines: warscrolls.map(summaryLine),
  }
}

/**
 * Turns the on-screen reminder list into the presentation-neutral print model shared by the PDF
 * renderer and the browser print view.
 */
export const createAos4PrintDocument = (
  reminders: PrintReminderInput[],
  army: PrintArmyInput
): PrintDocument => {
  const sections = reminders
    .filter(reminder => !reminder.hidden)
    .reduce<PrintSection[]>((accumulated, reminder) => {
      const existing = accumulated.find(section => section.key === reminder.windowKey)
      if (existing) {
        existing.rules.push(toRule(reminder))
        return accumulated
      }
      return [
        ...accumulated,
        { key: reminder.windowKey, heading: reminder.windowLabel, rules: [toRule(reminder)] },
      ]
    }, [])

  const summary = buildSummary(army)

  // An unnamed army falls back to the faction name, so don't print it twice.
  const showSubtitle = !!army.factionName && army.factionName.trim() !== army.armyName.trim()

  return {
    title: army.armyName,
    ...(showSubtitle ? { subtitle: army.factionName } : {}),
    sections,
    ...(summary ? { summary } : {}),
    footer: ['Generated by AoS Reminders', 'aosreminders.com'],
  }
}
