import type { PrintDocument, PrintParagraph, PrintRule, PrintSection, PrintTag } from './types'

/**
 * Structural subset of `Aos4ReminderViewModel`. Declared here so the print model does not depend on
 * the view layer and can be exercised with plain fixtures.
 */
export interface PrintReminderInput {
  id: string
  name: string
  windowKey: string
  windowLabel: string
  typeLabel: string
  /** Discrete timing facets. Absent on legacy fixtures, which fall back to `typeLabel`. */
  tags?: PrintTag[]
  declare?: string
  reactionTrigger?: string
  effect: string
  hidden: boolean
  note?: string
}

export interface PrintWarscrollInput {
  name: string
  profile?: {
    points?: number
    unitSize: number
  }
}

export interface PrintArmyInput {
  armyName: string
  factionName: string
  warscrolls?: PrintWarscrollInput[]
}

export interface PrintDocumentOptions {
  /** Defaults to true. Set false to omit the trailing warscroll summary from the print document. */
  includeSummary?: boolean
}

/** Wrapping reproduces text by joining on single spaces, so collapse runs of whitespace up front. */
const normalize = (value: string): string => value.replace(/\s+/g, ' ').trim()

const paragraphs = (reminder: PrintReminderInput): PrintParagraph[] => [
  ...(reminder.reactionTrigger
    ? [{ role: 'ruleBody' as const, label: 'Trigger', text: normalize(reminder.reactionTrigger) }]
    : []),
  ...(reminder.declare
    ? [{ role: 'ruleBody' as const, label: 'Declare', text: normalize(reminder.declare) }]
    : []),
  { role: 'ruleBody' as const, label: 'Effect', text: normalize(reminder.effect) },
  ...(reminder.note ? [{ role: 'ruleNote' as const, label: 'Note', text: normalize(reminder.note) }] : []),
]

/**
 * With tags present the facets are drawn as boxes, so the title is just the name. Without them the
 * old flattened prefix is kept, which is what lets legacy fixtures and any caller that has not
 * adopted tags keep working unchanged.
 */
const toRule = (reminder: PrintReminderInput): PrintRule => {
  const tags = reminder.tags ?? []
  if (tags.length) {
    return { id: reminder.id, title: reminder.name, tags, paragraphs: paragraphs(reminder) }
  }
  return {
    id: reminder.id,
    title: reminder.typeLabel ? `${reminder.typeLabel} - ${reminder.name}` : reminder.name,
    paragraphs: paragraphs(reminder),
  }
}

const summaryLine = (warscroll: PrintWarscrollInput): string => {
  if (!warscroll.profile) return warscroll.name
  const label = `${warscroll.name} (${warscroll.profile.unitSize})`
  return warscroll.profile.points === undefined ? label : `${label} - ${warscroll.profile.points} pts`
}

const buildSummary = (army: PrintArmyInput) => {
  const warscrolls = army.warscrolls ?? []
  if (!warscrolls.length) return undefined

  const points = warscrolls.reduce((total, warscroll) => total + (warscroll.profile?.points ?? 0), 0)
  return {
    heading: points ? `${army.armyName} - ${points} pts` : army.armyName,
    lines: warscrolls.map(summaryLine),
  }
}

/**
 * Turns the on-screen reminder list into the presentation-neutral print model shared by the PDF
 * renderer and the browser print view.
 */
export const createAos4PrintDocument = (
  reminders: PrintReminderInput[],
  army: PrintArmyInput,
  options: PrintDocumentOptions = {}
): PrintDocument => {
  const sections = reminders
    .filter(reminder => !reminder.hidden)
    .reduce<PrintSection[]>((accumulated, reminder) => {
      const existing = accumulated.find(section => section.key === reminder.windowKey)
      if (existing) {
        existing.rules.push(toRule(reminder))
        return accumulated
      }
      return [
        ...accumulated,
        { key: reminder.windowKey, heading: reminder.windowLabel, rules: [toRule(reminder)] },
      ]
    }, [])

  const summary = options.includeSummary === false ? undefined : buildSummary(army)

  // An unnamed army falls back to the faction name, so don't print it twice.
  const showSubtitle = !!army.factionName && army.factionName.trim() !== army.armyName.trim()

  return {
    title: army.armyName,
    ...(showSubtitle ? { subtitle: army.factionName } : {}),
    sections,
    ...(summary ? { summary } : {}),
    footer: ['Generated by AoS Reminders', 'aosreminders.com'],
  }
}
